name: Run Tests and Deploy Report

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-html

      - name: Run tests and generate report
        run: |
          pytest tests/api --html=report.html --self-contained-html

      - name: Copy report to docs folder
        run: |
          mkdir -p docs
          cp report.html docs/index.html

      - name: Commit and push test report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/index.html || echo "Nothing to add"
          git commit -m "Update test report [skip ci]" || echo "Nothing to commit"
          git status
          git log -1
          git remote -v
          git push || echo "Push failed"

          # Triggering re-run